-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create/Update Teachers Table
create table if not exists teachers (
  id text primary key,
  name text not null,
  subject text,
  whatsapp text,
  lesson_link text,
  exam_link text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Ensure all new columns exist
alter table teachers add column if not exists is_active boolean default true;
alter table teachers add column if not exists subscription_tier text default 'basic';
alter table teachers add column if not exists trial_expires_at timestamp with time zone default (now() + interval '7 days');

-- 2. Create Students Table
create table if not exists students (
  id bigint generated by default as identity primary key,
  name text not null,
  whatsapp text,
  teacher_id text references teachers(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Enable RLS and Policies
alter table teachers enable row level security;
alter table students enable row level security;

-- Policies (using do block to avoid errors if they exist)
do $$ 
begin
    if not exists (select 1 from pg_policies where policyname = 'Allow public read for teachers') then
        create policy "Allow public read for teachers" on teachers for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public insert for teachers') then
        create policy "Allow public insert for teachers" on teachers for insert with check (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public update for teachers') then
        create policy "Allow public update for teachers" on teachers for update using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public read for students') then
        create policy "Allow public read for students" on students for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public insert for students') then
        create policy "Allow public insert for students" on students for insert with check (true);
    end if;
end $$;
-- 4. Create Classes Table (for virtual room history)
create table if not exists classes (
  id text primary key,
  teacher_id text references teachers(id) on delete cascade,
  title text,
  sessions jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Create Attendance Table (tracking student participation)
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  class_id text references classes(id) on delete cascade,
  student_name text,
  student_whatsapp text,
  entered_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Enable RLS and Policies for new tables
alter table classes enable row level security;
alter table attendance enable row level security;

-- 7. Create Exams Table
create table if not exists exams (
  id text primary key,
  teacher_id text references teachers(id) on delete cascade,
  title text not null,
  duration int default 30,
  shuffle boolean default false,
  description text,
  questions jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table exams enable row level security;

do $$ 
begin
    -- Classes policies
    if not exists (select 1 from pg_policies where policyname = 'Allow public read for classes') then
        create policy "Allow public read for classes" on classes for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public insert for classes') then
        create policy "Allow public insert for classes" on classes for insert with check (true);
    end if;
    
    -- Attendance policies
    if not exists (select 1 from pg_policies where policyname = 'Allow public read for attendance') then
        create policy "Allow public read for attendance" on attendance for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public insert for attendance') then
        create policy "Allow public insert for attendance" on attendance for insert with check (true);
    end if;

    -- Exams policies
    if not exists (select 1 from pg_policies where policyname = 'Allow public read for exams') then
        create policy "Allow public read for exams" on exams for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow teacher insert for exams') then
        create policy "Allow teacher insert for exams" on exams for insert with check (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow teacher update for exams') then
        create policy "Allow teacher update for exams" on exams for update using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow teacher delete for exams') then
        create policy "Allow teacher delete for exams" on exams for delete using (true);
    end if;

    -- Results Table
    execute 'create table if not exists results (
      id text primary key,
      teacher_id text references teachers(id) on delete cascade,
      student_id text,
      student_name text,
      student_phone text,
      exam_id text references exams(id) on delete cascade,
      exam_title text,
      score int,
      total int,
      percentage int,
      answers jsonb,
      time_taken int,
      submitted_at bigint,
      auto_submitted boolean,
      created_at timestamp with time zone default timezone(''utc''::text, now())
    )';

    if not exists (select 1 from pg_tables where tablename = 'results') then
        alter table results enable row level security;
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Allow teacher read for results') then
        create policy "Allow teacher read for results" on results for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Allow public insert for results') then
        create policy "Allow public insert for results" on results for insert with check (true);
    end if;
end $$;
